// The included JNI surface is machine-generated and intentionally favors
// uniform templates over hand-written Clippy idioms. Keep warnings strict for
// every other lint while acknowledging the generator's known patterns.
#![allow(
    clippy::blocks_in_conditions,
    clippy::clone_on_copy,
    clippy::extra_unused_lifetimes,
    clippy::let_unit_value,
    clippy::missing_safety_doc,
    clippy::needless_borrows_for_generic_args,
    clippy::unnecessary_map_on_constructor,
    clippy::unused_unit,
    clippy::useless_conversion
)]

// Binding-local `Duration` millisecond converters referenced by the generated
// bindings (declared via `convert!(Duration)` in build.rs).
mod duration;
pub use duration::{duration_from_millis, duration_to_millis};

// Fix for https://github.com/eclipse-zenoh/zenoh-flat-jni/issues/49: pins the
// `io.zenoh.jni.*` `fromParts` factory classes at library-load time so
// delivery from Zenoh's own background threads doesn't need `FindClass`.
mod class_cache;

// Generated by build.rs into src/generated_bindings.rs
include!("generated_bindings.rs");

// Hand-written ZBytes serialization JNI. Java-specific (walks reflect.Type,
// builds java.util collections), so it lives here rather than in the
// language-agnostic zenoh-flat. Throws io.zenoh.jni.JniBindingError via the
// generated `throw_JniBindingError`.
#[cfg(feature = "zenoh-ext")]
mod zbytes;
